# Generated by Django 5.0.3 on 2024-05-26 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_attendence_attendenceon_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='AttendenceOn',
            field=models.DateField(default=datetime.datetime(2024, 5, 26, 20, 11, 57, 550538)),
        ),
    ]
