# Generated by Django 5.0.3 on 2024-05-26 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_attendence_attendenceon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='AttendenceOn',
            field=models.DateField(default=datetime.datetime(2024, 5, 26, 21, 40, 6, 118451)),
        ),
        migrations.AlterField(
            model_name='homework',
            name='student',
            field=models.CharField(max_length=250, verbose_name='Фамилия'),
        ),
    ]
