# Generated by Django 5.0.3 on 2024-05-26 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_attendence_attendenceon_alter_homework_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='AttendenceOn',
            field=models.DateField(default=datetime.datetime(2024, 5, 26, 21, 46, 41, 424936)),
        ),
        migrations.CreateModel(
            name='marking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(choices=[(5, 'Amazing'), (4, 'Good'), (3, 'Normal'), (2, 'Bad')])),
                ('student', models.ManyToManyField(to='main.homework')),
            ],
        ),
    ]
