# Generated by Django 5.0.3 on 2024-05-26 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_attendence_attendenceon_marking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='AttendenceOn',
            field=models.DateField(default=datetime.datetime(2024, 5, 26, 22, 5, 59, 15650)),
        ),
    ]
