# Generated by Django 5.0.6 on 2024-05-26 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_attendence_attendenceon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='AttendenceOn',
            field=models.DateField(default=datetime.datetime(2024, 5, 26, 23, 30, 6, 163289)),
        ),
    ]
